-- ====================================================================
-- ตารางเก็บข้อมูลแบบลงทะเบียนและแบบประเมินความพึงพอใจ
-- บูธ "แม่ไก่ใส่ใจลูกเจี๊ยบ" โรงเรียนอุเทนพัฒนา สพม.นครพนม
-- --------------------------------------------------------------------
-- วิธีใช้: เปิด Supabase Dashboard > SQL Editor > วางสคริปต์นี้ > Run
--
-- สถานะ: รันแล้วในโปรเจกต์ physics-utp (vhbbgjbojlifelncyide)
-- ซึ่งเป็นโปรเจกต์ที่ booth-config.js ชี้ไปอยู่ในขณะนี้
-- เก็บไฟล์นี้ไว้เพื่อใช้ย้ายไปโปรเจกต์อื่นหรือสร้างใหม่ในภายหลัง
-- ====================================================================

create table if not exists public.booth_visits (
    id                bigint generated by default as identity primary key,
    created_at        timestamptz not null default now(),

    -- ตอนที่ 1: ข้อมูลผู้เข้าเยี่ยมชม (แบบลงทะเบียน)
    visitor_name      text not null,
    gender            text,
    visitor_type      text,
    edu_level         text,
    organization      text,
    province          text,
    contact           text,
    visit_round       text,
    referral_sources  jsonb default '[]'::jsonb,

    -- ตอนที่ 2: คะแนนความพึงพอใจ 15 ข้อ เก็บเป็น JSON เช่น {"c1":5,"c2":4,...}
    ratings           jsonb not null default '{}'::jsonb,
    avg_score         numeric(3,2),

    -- ตอนที่ 3: ภาพรวมและข้อเสนอแนะ
    overall_rating    smallint check (overall_rating between 1 and 5),
    impressed         text,
    suggestion        text
);

-- ดัชนีช่วยให้แดชบอร์ดเรียงข้อมูลได้เร็วขึ้น
create index if not exists booth_visits_created_at_idx
    on public.booth_visits (created_at desc);

-- --------------------------------------------------------------------
-- Row Level Security
-- เปิด RLS แล้วอนุญาตให้ผู้ใช้ทั่วไป (anon) เพิ่มและอ่านข้อมูลได้
-- เนื่องจากเป็นแบบประเมินสาธารณะหน้าบูธที่ไม่มีระบบล็อกอิน
-- หมายเหตุ: ไม่เปิดสิทธิ์ update/delete ให้ anon เพื่อป้องกันการแก้ไข/ลบข้อมูล
-- --------------------------------------------------------------------
alter table public.booth_visits enable row level security;

drop policy if exists "booth_visits_public_insert" on public.booth_visits;
create policy "booth_visits_public_insert"
    on public.booth_visits
    for insert
    to anon, authenticated
    with check (true);

drop policy if exists "booth_visits_public_select" on public.booth_visits;
create policy "booth_visits_public_select"
    on public.booth_visits
    for select
    to anon, authenticated
    using (true);

-- --------------------------------------------------------------------
-- (ทางเลือก) มุมมองสรุปค่าเฉลี่ยรายด้าน สำหรับนำไปทำรายงานใน Supabase โดยตรง
-- --------------------------------------------------------------------
-- ใช้ security_invoker เพื่อให้มุมมองนี้ทำงานด้วยสิทธิ์ของผู้เรียก (ผ่าน RLS ตามปกติ)
create or replace view public.booth_visits_summary
with (security_invoker = true) as
select
    count(*)                                   as total_visitors,
    round(avg(avg_score), 2)                   as overall_mean,
    round(stddev_samp(avg_score), 2)           as overall_sd,
    round(avg(overall_rating), 2)              as overall_star_mean,
    count(*) filter (where avg_score >= 3.51)  as satisfied_count
from public.booth_visits;
